### ISSUE TITLE
Create requirements

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/software_types#2]
I started drafting `cqs.csv` so we can add the rationale for our classes and properties

**Comment by proycon** [comment]
I already filled the `cqs.csv` a bit a while back, does this agree with what you had in mind?

**Comment by dgarijo** [comment]
Yes. I think the rationale bit needs a little iteration. Let me have a look and come back to this issue with my questions

**Comment by dgarijo** [comment]
closing this one, as I raised questions in separate issues
